### ISSUE TITLE
./installGhostbusters.sh does not compile sources

### ISSUE THREAD

**Issue by michaeljyeates** [HKEOS/Ghostbusters-Testnet#17]
If the sources directory doesnt exist then it fails with this error

`EOS_SOURCE_DIR="/home/dac/eos-ghostbusters"`

```$ ./installGhostbusters.sh 
Configuration done!
Work directory: ghostbusters-eosdacserver
fatal: Cannot change to '/home/dac/eos-ghostbusters': No such file or directory

**Comment by jchung00** [comment]
Not a current feature but it would be good to have. Thanks for posting this.

**Comment by jchung00** [comment]
Solved.
https://github.com/HKEOS/Ghostbusters-Testnet/commit/735dba0a35264a52c4883e24f1a69df632c2490b
