### ISSUE TITLE
Typo???

### ISSUE THREAD

**Issue by khosimorafo** [HKEOS/Ghostbusters-Testnet#2]
Can I change this? Seem a typo. Not sure of impact.

https://github.com/HKEOS/Ghostbusters-Testnet/blob/a6d7b2dc0a9be06711b761aecc5c916f88fa822c/params.sh#L44

**Comment by jchung00** [comment]
We used PRODUSER_NAME everywhere on the scripts, so it shouldn't have an impact. It is the wrong spelling though...
