### ISSUE TITLE
Install instructions to include: touch a file under ~/kbfs/team/eos_ghostbusters/ip_list  with node name and wire guard IP they are using (this is to prevent multiple BPs from using same IP address)

### ISSUE THREAD

**Issue by nksanthosh** [HKEOS/Ghostbusters-Testnet#20]
Install instructions to include: touch a file under ~/kbfs/team/eos_ghostbusters/ip_list  with node name and wire guard IP they are using (this is to prevent multiple BPs from using same IP address)

**Comment by jchung00** [comment]
Added.
