### ISSUE TITLE
Consider using graphene blockchain vs bitcoin for target launch block

### ISSUE THREAD

**Issue by educatedwarrior** [HKEOS/Ghostbusters-Testnet#24]
Just a suggestion.   We had issues with the launch on 5/27 using Bitcoin since the blocks were being mined faster than expected.  This is under the assumption graphene blocks are produced at a more consistent rate.  Jae asked me to add this suggestion here.

**Comment by igorls** [comment]
That is very good actually, what reliable APIs do we have?

**Comment by educatedwarrior** [comment]
I was thinking Bitshares or Steem.

**Comment by educatedwarrior** [comment]
http://docs.bitshares.org/api/database.html

**Comment by jchung00** [comment]
`autolaunch.sh` won't be used anymore
