### ISSUE TITLE
Cant get the existing IP list

### ISSUE THREAD

**Issue by helloravi** [HKEOS/Ghostbusters-Testnet#41]
Not able to make this work:

cd ~/kbfs/team/eos_ghostbusters/ip_list
ls
You will see the list of IP addresses that have already been claimed
 Choose an address that is open
touch <chosen-ip-address>@<your-node-name>
This adds a file with your IP address to the ip_list folder in an easy to sort format

**Comment by jchung00** [comment]
What is your keybase username? You might not have write access

**Comment by helloravi** [comment]
eoswest

**Comment by jchung00** [comment]
please request to join keybase group we haven't received a request from that account yet
